# Generated by Django 3.2.9 on 2021-11-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(max_length=355, verbose_name='Biografia'),
        ),
    ]
