# Generated by Django 3.2.9 on 2021-11-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_student_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.DateField(verbose_name='Data nascimento'),
        ),
    ]
