# Generated by Django 3.2.9 on 2021-12-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_student_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.AddField(
            model_name='student',
            name='atividades_extras',
            field=models.JSONField(default={}, verbose_name='Atividades extras'),
        ),
        migrations.AddField(
            model_name='student',
            name='cidade',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='student',
            name='conhecimento_tecnico',
            field=models.JSONField(default={}, verbose_name='Conhecimento técnico'),
        ),
        migrations.AddField(
            model_name='student',
            name='curso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='student',
            name='experiencia',
            field=models.TextField(blank=True, verbose_name='Experiência'),
        ),
        migrations.AddField(
            model_name='student',
            name='formacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Formação'),
        ),
        migrations.AddField(
            model_name='student',
            name='gitHub',
            field=models.CharField(blank=True, max_length=255, verbose_name='Github'),
        ),
        migrations.AddField(
            model_name='student',
            name='idioma',
            field=models.JSONField(null=True, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='student',
            name='telefone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=255, verbose_name='E-mail'),
        ),
    ]
